apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: PostgreSQL
      type: postgres
      access: proxy
      url: postgresql.postgres.svc.cluster.local:5432
      database: postgres
      user: admin
      secureJsonData:
        password: admin123
      jsonData:
        sslmode: disable
        postgresVersion: 1400
        timescaledb: false